name: inspector_for_perception
description: A widget for visualising state change in apps using astro.
version: 0.0.0-a1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  collection: ^1.17.1
  
  core_of_perception: ^0.0.0-a1
  error_handling_for_perception: ^0.0.0-a1
  locator_for_perception: ^0.0.0-a1
  types_for_perception: ^0.0.0-a1

dev_dependencies:
  flutter_test:
    sdk: flutter
  enspyr_lints: ^0.0.0-a1
  test_utils_for_perception: ^0.0.0-a1

flutter:
   fonts:
    - family:  IconsFontFamily
      fonts:
       - asset: fonts/IconsFont.ttf