name: introspection
description: A widget for visualising belief updating in apps using perception.
version: 0.0.0-a1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  collection: ^1.17.1
  flutter_fancy_tree_view: ^1.3.0
  
  percepts:
    git: https://github.com/enspyrco/percepts
  abstractions:
    git: https://github.com/enspyrco/abstractions
  locator_for_perception:
    git: https://github.com/enspyrco/locator_for_perception
  error_correction_in_perception:
    git: https://github.com/enspyrco/error_correction_in_perception

  types_for_auth:
    git: https://github.com/enspyrco/types_for_auth
  json_utils:
    git: https://github.com/enspyrco/json_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  enspyr_lints:
    git: https://github.com/enspyrco/enspyr_lints
  test_utils_for_perception:
    git: https://github.com/enspyrco/test_utils_for_perception

flutter:
  fonts:
    - family:  IconsFontFamily
      fonts:
        - asset: fonts/IconsFont.ttf
